// Generated by scripts/render-globe.mjs (`pnpm render-globe`); edit that
// and re-run it, not this. The globe's disc is centred in the image, so its
// centre is the image's centre; the clouds either side set its width.
import globeUrl from "./globe.webp";

/** Width / height of the image, clouds included. */
export const GLOBE_ASPECT = 625 / 480;

interface GlobeProps {
  className?: string;
}

export default function Globe({ className = "" }: GlobeProps) {
  return (
    <img
      src={globeUrl}
      width={625}
      height={480}
      alt=""
      aria-hidden
      draggable={false}
      decoding="async"
      className={`block select-none ${className}`}
    />
  );
}
