// Generated by scripts/pixel-globe.py; edit that and re-run it, not this.
// Pixel art: an orthographic view of the Atlantic on a 43x32
// grid, one path per colour. Crisp edges keep the pixels square at any size;
// size it with the className (height drives width). The disc fills the full
// height, so its centre is the SVG's centre.

/** Width / height of the whole drawing, clouds included. */
export const PIXEL_GLOBE_ASPECT = 43 / 32;

interface PixelGlobeProps {
  className?: string;
}

export default function PixelGlobe({ className = "" }: PixelGlobeProps) {
  return (
    <svg
      viewBox="0 0 43 32"
      shapeRendering="crispEdges"
      aria-hidden
      className={`block ${className}`}
    >
      <path fill="#6F88E8" d="M18 1h4v1h-4zM13 2h1v1h-1zM18 2h1v1h-1zM21 2h2v1h-2zM13 3h1v1h-1zM20 5h1v1h-1zM9 6h2v1h-2zM19 6h2v1h-2zM8 7h2v1h-2zM20 7h1v1h-1zM22 7h1v1h-1zM8 8h1v1h-1zM20 8h2v1h-2zM7 9h2v1h-2zM20 9h2v1h-2zM7 10h2v1h-2zM19 10h2v1h-2zM7 11h2v1h-2zM17 11h3v1h-3zM7 12h2v1h-2zM16 12h3v1h-3zM7 13h2v1h-2zM15 13h3v1h-3zM7 14h2v1h-2zM11 14h6v1h-6zM8 15h1v1h-1zM12 15h3v1h-3z" />
      <path fill="#3B5BDB" d="M18 0h6v1h-6zM22 1h2v1h-2zM23 2h3v1h-3zM25 3h2v1h-2zM25 4h2v1h-2zM24 5h3v1h-3zM23 6h5v1h-5zM29 6h1v1h-1zM23 7h4v1h-4zM22 8h5v1h-5zM28 8h1v1h-1zM22 9h7v1h-7zM21 10h8v1h-8zM20 11h9v1h-9zM6 12h1v1h-1zM19 12h10v1h-10zM6 13h1v1h-1zM18 13h10v1h-10zM6 14h1v1h-1zM17 14h11v1h-11zM6 15h2v1h-2zM15 15h12v1h-12zM6 16h3v1h-3zM12 16h14v1h-14zM6 17h4v1h-4zM13 17h12v1h-12zM6 18h5v1h-5zM13 18h11v1h-11zM6 19h5v1h-5zM12 19h1v1h-1zM17 19h6v1h-6zM7 20h6v1h-6zM18 20h4v1h-4zM7 21h5v1h-5zM8 22h4v1h-4zM10 23h2v1h-2z" />
      <path fill="#3451C7" d="M32 10h3v1h-3zM28 13h1v1h-1zM28 14h1v1h-1zM27 15h2v1h-2zM26 16h2v1h-2zM25 17h3v1h-3zM24 18h4v1h-4zM23 19h6v1h-6zM22 20h7v1h-7zM33 20h1v1h-1zM20 21h10v1h-10zM32 21h2v1h-2zM7 22h1v1h-1zM21 22h14v1h-14zM8 23h2v1h-2zM22 23h12v1h-12zM8 24h4v1h-4zM25 24h9v1h-9zM9 25h4v1h-4zM25 25h8v1h-8zM10 26h4v1h-4zM24 26h8v1h-8zM12 27h3v1h-3zM24 27h7v1h-7zM23 28h6v1h-6zM21 29h6v1h-6z" />
      <path fill="#2F44B0" d="M34 23h1v1h-1zM33 25h1v1h-1zM32 26h2v1h-2zM11 27h1v1h-1zM12 28h3v1h-3zM13 29h2v1h-2zM20 30h6v1h-6zM18 31h8v1h-8z" />
      <path fill="#26399A" d="M17 1h1v1h-1zM24 1h2v1h-2zM17 2h1v1h-1zM20 2h1v1h-1zM26 2h2v1h-2zM18 3h1v1h-1zM24 3h1v1h-1zM20 4h1v1h-1zM24 4h1v1h-1zM16 5h2v1h-2zM19 5h1v1h-1zM23 5h1v1h-1zM27 5h1v1h-1zM29 5h1v1h-1zM16 6h1v1h-1zM18 6h1v1h-1zM22 6h1v1h-1zM28 6h1v1h-1zM16 7h1v1h-1zM19 7h1v1h-1zM21 7h1v1h-1zM28 7h1v1h-1zM33 7h1v1h-1zM19 8h1v1h-1zM27 8h1v1h-1zM19 9h1v1h-1zM32 9h3v1h-3zM17 10h2v1h-2zM30 10h2v1h-2zM15 11h2v1h-2zM30 11h1v1h-1zM33 11h1v1h-1zM15 12h1v1h-1zM29 12h1v1h-1zM10 13h5v1h-5zM10 14h1v1h-1zM11 15h1v1h-1zM9 16h1v1h-1zM11 16h1v1h-1zM10 17h1v1h-1zM12 17h1v1h-1zM12 18h1v1h-1zM28 18h1v1h-1zM11 19h1v1h-1zM16 19h1v1h-1zM33 19h1v1h-1zM17 20h1v1h-1zM29 20h1v1h-1zM32 20h1v1h-1zM19 21h1v1h-1zM30 21h2v1h-2zM34 21h1v1h-1zM20 22h1v1h-1zM21 23h1v1h-1zM12 24h1v1h-1zM24 24h1v1h-1zM13 25h1v1h-1zM24 25h1v1h-1zM14 26h1v1h-1zM23 26h1v1h-1zM23 27h1v1h-1zM21 28h2v1h-2zM20 29h1v1h-1zM15 30h1v1h-1zM18 30h2v1h-2z" />
      <path fill="#C3E4CE" d="M15 1h2v1h-2zM28 1h1v1h-1zM15 2h2v1h-2zM19 2h1v1h-1zM14 3h1v1h-1zM17 3h1v1h-1zM20 3h1v1h-1zM22 3h1v1h-1zM16 4h1v1h-1zM28 4h1v1h-1zM11 6h3v1h-3zM15 6h1v1h-1zM15 7h1v1h-1zM17 7h1v1h-1zM27 7h1v1h-1zM30 7h1v1h-1zM9 8h1v1h-1zM18 8h1v1h-1zM12 9h1v1h-1zM14 9h1v1h-1zM16 9h1v1h-1zM18 9h1v1h-1zM31 9h1v1h-1zM10 10h1v1h-1zM16 10h1v1h-1zM11 11h1v1h-1zM13 11h2v1h-2zM35 11h1v1h-1zM13 12h1v1h-1zM10 15h1v1h-1zM31 15h1v1h-1zM35 15h1v1h-1zM30 16h1v1h-1zM34 16h1v1h-1zM31 17h1v1h-1zM11 18h1v1h-1zM34 18h1v1h-1zM13 19h1v1h-1zM29 19h1v1h-1zM18 22h1v1h-1zM16 27h1v1h-1z" />
      <path fill="#9CCBB2" d="M25 0h1v1h-1zM26 1h2v1h-2zM14 2h1v1h-1zM28 2h3v1h-3zM15 3h2v1h-2zM19 3h1v1h-1zM21 3h1v1h-1zM23 3h1v1h-1zM28 3h3v1h-3zM15 4h1v1h-1zM18 4h1v1h-1zM21 4h1v1h-1zM23 4h1v1h-1zM27 4h1v1h-1zM29 4h4v1h-4zM15 5h1v1h-1zM18 5h1v1h-1zM21 5h2v1h-2zM28 5h1v1h-1zM30 5h4v1h-4zM17 6h1v1h-1zM21 6h1v1h-1zM30 6h4v1h-4zM10 7h5v1h-5zM18 7h1v1h-1zM29 7h1v1h-1zM31 7h2v1h-2zM10 8h1v1h-1zM12 8h3v1h-3zM16 8h2v1h-2zM29 8h5v1h-5zM9 9h3v1h-3zM13 9h1v1h-1zM15 9h1v1h-1zM17 9h1v1h-1zM29 9h2v1h-2zM12 10h4v1h-4zM29 10h1v1h-1zM10 11h1v1h-1zM12 11h1v1h-1zM29 11h1v1h-1zM31 11h2v1h-2zM9 12h4v1h-4zM14 12h1v1h-1zM30 12h5v1h-5zM9 13h1v1h-1zM29 13h6v1h-6zM9 14h1v1h-1zM29 14h7v1h-7zM9 15h1v1h-1zM30 15h1v1h-1zM32 15h3v1h-3zM29 16h1v1h-1zM31 16h1v1h-1zM35 16h1v1h-1zM11 17h1v1h-1zM28 17h3v1h-3zM33 17h3v1h-3zM29 18h3v1h-3zM33 18h1v1h-1zM35 18h1v1h-1zM14 19h2v1h-2zM30 19h3v1h-3zM34 19h2v1h-2zM13 20h1v1h-1zM15 20h2v1h-2zM30 20h2v1h-2zM34 20h2v1h-2zM12 21h7v1h-7zM12 22h1v1h-1zM14 22h3v1h-3zM19 22h1v1h-1zM12 23h6v1h-6zM19 23h2v1h-2zM13 24h10v1h-10zM14 25h8v1h-8zM23 25h1v1h-1zM15 26h1v1h-1zM17 26h4v1h-4zM15 27h1v1h-1zM17 27h3v1h-3zM21 27h2v1h-2zM15 28h1v1h-1zM17 28h4v1h-4zM17 29h3v1h-3z" />
      <path fill="#7FB598" d="M34 6h1v1h-1zM34 7h2v1h-2zM34 8h2v1h-2zM35 9h2v1h-2zM35 10h2v1h-2zM36 14h2v1h-2zM36 15h2v1h-2zM36 16h2v1h-2zM36 17h2v1h-2zM36 18h2v1h-2zM36 19h2v1h-2zM36 20h1v1h-1zM35 21h2v1h-2zM35 22h2v1h-2zM35 23h1v1h-1zM34 24h2v1h-2zM34 25h1v1h-1zM15 29h2v1h-2zM16 30h2v1h-2z" />
      <path fill="#5E9C73" d="M24 0h1v1h-1zM27 3h1v1h-1zM31 3h1v1h-1zM17 4h1v1h-1zM19 4h1v1h-1zM22 4h1v1h-1zM14 6h1v1h-1zM11 8h1v1h-1zM15 8h1v1h-1zM9 10h1v1h-1zM11 10h1v1h-1zM9 11h1v1h-1zM34 11h1v1h-1zM29 15h1v1h-1zM10 16h1v1h-1zM28 16h1v1h-1zM32 16h2v1h-2zM32 17h1v1h-1zM32 18h1v1h-1zM14 20h1v1h-1zM13 22h1v1h-1zM17 22h1v1h-1zM18 23h1v1h-1zM23 24h1v1h-1zM22 25h1v1h-1zM16 26h1v1h-1zM21 26h2v1h-2zM20 27h1v1h-1zM16 28h1v1h-1z" />
      <path fill="#FFFFFF" d="M8 2h4v1h-4zM6 3h2v1h-2zM12 3h1v1h-1zM4 4h3v1h-3zM14 4h1v1h-1zM0 5h2v1h-2zM37 10h3v1h-3zM36 11h1v1h-1zM40 11h2v1h-2zM35 12h1v1h-1zM31 27h4v1h-4zM29 28h2v1h-2zM35 28h2v1h-2zM27 29h2v1h-2zM37 29h3v1h-3zM26 30h1v1h-1zM41 30h1v1h-1z" />
      <path fill="#D6E8F8" d="M8 3h4v1h-4zM7 4h7v1h-7zM13 5h2v1h-2zM37 11h3v1h-3zM36 12h7v1h-7zM31 28h4v1h-4zM29 29h8v1h-8zM27 30h14v1h-14z" />
      <path fill="#B4B8F0" d="M2 5h11v1h-11zM0 6h2v1h-2zM35 13h8v1h-8zM26 31h16v1h-16z" />
    </svg>
  );
}
