// Generated by scripts/pixel-globe.py; edit that and re-run it, not this.
// Pixel art: an orthographic view of the Atlantic on a 54x40 grid, one
// path per colour. Crisp edges keep the pixels square at any size; size it
// with the className (height drives width). The disc fills the full height,
// so its centre is the SVG's centre.

/** Width / height of the whole drawing, clouds included. */
export const PIXEL_GLOBE_ASPECT = 54 / 40;

interface PixelGlobeProps {
  className?: string;
}

export default function PixelGlobe({ className = "" }: PixelGlobeProps) {
  return (
    <svg
      viewBox="0 0 54 40"
      shapeRendering="crispEdges"
      aria-hidden
      className={`block ${className}`}
    >
      <path fill="#7F97EC" d="M23 6h1v1h-1zM22 7h1v1h-1zM23 8h1v1h-1zM22 9h1v1h-1zM24 9h1v1h-1zM23 10h1v1h-1zM18 11h2v1h-2zM21 11h2v1h-2zM24 11h1v1h-1zM17 12h1v1h-1zM19 12h1v1h-1zM21 12h1v1h-1zM23 12h1v1h-1zM16 13h1v1h-1zM18 13h3v1h-3zM22 13h1v1h-1zM15 14h1v1h-1zM17 14h1v1h-1zM19 14h1v1h-1zM21 14h1v1h-1zM14 15h1v1h-1zM16 15h1v1h-1zM18 15h1v1h-1zM20 15h1v1h-1zM22 15h1v1h-1zM18 17h1v1h-1z" />
      <path fill="#5874E2" d="M23 4h1v1h-1zM23 5h1v1h-1zM28 5h1v1h-1zM30 5h1v1h-1zM18 6h1v1h-1zM22 6h1v1h-1zM27 6h1v1h-1zM23 7h1v1h-1zM25 7h3v1h-3zM29 7h2v1h-2zM22 8h1v1h-1zM24 8h6v1h-6zM23 9h1v1h-1zM25 9h6v1h-6zM22 10h1v1h-1zM24 10h6v1h-6zM23 11h1v1h-1zM25 11h6v1h-6zM18 12h1v1h-1zM20 12h1v1h-1zM22 12h1v1h-1zM24 12h4v1h-4zM29 12h1v1h-1zM17 13h1v1h-1zM21 13h1v1h-1zM23 13h6v1h-6zM30 13h1v1h-1zM16 14h1v1h-1zM18 14h1v1h-1zM20 14h1v1h-1zM22 14h6v1h-6zM29 14h1v1h-1zM11 15h3v1h-3zM15 15h1v1h-1zM17 15h1v1h-1zM19 15h1v1h-1zM21 15h1v1h-1zM23 15h6v1h-6zM11 16h15v1h-15zM27 16h1v1h-1zM14 17h4v1h-4zM19 17h2v1h-2zM24 17h3v1h-3zM13 18h6v1h-6zM12 19h11v1h-11zM24 19h1v1h-1zM13 20h1v1h-1zM15 20h1v1h-1zM17 20h1v1h-1zM19 20h1v1h-1zM21 20h1v1h-1zM23 20h1v1h-1zM14 21h1v1h-1zM16 21h1v1h-1zM18 21h1v1h-1zM20 21h1v1h-1zM22 21h1v1h-1z" />
      <path fill="#3B5BDB" d="M24 1h6v1h-6zM27 2h5v1h-5zM29 3h5v1h-5zM29 4h3v1h-3zM29 5h1v1h-1zM31 5h1v1h-1zM30 6h2v1h-2zM31 7h1v1h-1zM30 8h1v1h-1zM30 10h1v1h-1zM31 11h2v1h-2zM28 12h1v1h-1zM30 12h2v1h-2zM29 13h1v1h-1zM31 13h1v1h-1zM35 13h4v1h-4zM28 14h1v1h-1zM30 14h2v1h-2zM29 15h4v1h-4zM26 16h1v1h-1zM28 16h5v1h-5zM8 17h1v1h-1zM27 17h5v1h-5zM8 18h1v1h-1zM26 18h5v1h-5zM8 19h2v1h-2zM23 19h1v1h-1zM25 19h6v1h-6zM8 20h2v1h-2zM12 20h1v1h-1zM14 20h1v1h-1zM16 20h1v1h-1zM18 20h1v1h-1zM20 20h1v1h-1zM22 20h1v1h-1zM24 20h7v1h-7zM8 21h2v1h-2zM11 21h3v1h-3zM15 21h1v1h-1zM17 21h1v1h-1zM19 21h1v1h-1zM21 21h1v1h-1zM23 21h8v1h-8zM8 22h4v1h-4zM16 22h15v1h-15zM9 23h3v1h-3zM18 23h13v1h-13zM9 24h2v1h-2zM18 24h13v1h-13zM9 25h2v1h-2zM20 25h11v1h-11zM21 26h7v1h-7zM29 26h1v1h-1zM10 27h1v1h-1zM21 27h6v1h-6zM28 27h1v1h-1zM25 28h1v1h-1z" />
      <path fill="#3451C7" d="M39 13h3v1h-3zM39 14h1v1h-1zM31 25h1v1h-1zM9 26h2v1h-2zM28 26h1v1h-1zM30 26h6v1h-6zM27 27h1v1h-1zM29 27h8v1h-8zM10 28h2v1h-2zM24 28h1v1h-1zM26 28h8v1h-8zM11 29h1v1h-1zM28 29h5v1h-5zM34 29h1v1h-1zM11 30h2v1h-2zM30 30h2v1h-2zM12 31h2v1h-2zM25 31h6v1h-6zM13 32h1v1h-1zM24 32h4v1h-4zM14 33h1v1h-1zM24 33h1v1h-1zM26 33h1v1h-1z" />
      <path fill="#2F44B0" d="M37 25h1v1h-1zM36 26h3v1h-3zM37 27h2v1h-2zM34 28h6v1h-6zM33 29h1v1h-1zM35 29h5v1h-5zM32 30h7v1h-7zM31 31h8v1h-8zM28 32h11v1h-11zM25 33h1v1h-1zM27 33h11v1h-11zM23 34h11v1h-11zM21 35h11v1h-11zM20 36h10v1h-10zM20 37h8v1h-8zM24 38h6v1h-6z" />
      <path fill="#293D9F" d="M26 2h1v1h-1zM32 2h2v1h-2zM20 3h4v1h-4zM28 3h1v1h-1zM22 4h1v1h-1zM28 4h1v1h-1zM18 5h2v1h-2zM22 5h1v1h-1zM27 5h1v1h-1zM17 6h1v1h-1zM20 6h2v1h-2zM25 6h2v1h-2zM29 6h1v1h-1zM34 6h1v1h-1zM21 7h1v1h-1zM24 7h1v1h-1zM28 7h1v1h-1zM32 7h1v1h-1zM21 8h1v1h-1zM32 8h2v1h-2zM41 8h1v1h-1zM21 9h1v1h-1zM39 9h2v1h-2zM18 10h2v1h-2zM21 10h1v1h-1zM31 10h2v1h-2zM39 10h1v1h-1zM17 11h1v1h-1zM20 11h1v1h-1zM15 12h2v1h-2zM35 12h5v1h-5zM15 13h1v1h-1zM34 13h1v1h-1zM10 14h5v1h-5zM32 14h1v1h-1zM38 14h1v1h-1zM10 15h1v1h-1zM10 16h1v1h-1zM44 16h1v1h-1zM11 17h1v1h-1zM13 17h1v1h-1zM9 18h1v1h-1zM11 18h2v1h-2zM11 19h1v1h-1zM11 20h1v1h-1zM10 21h1v1h-1zM15 22h1v1h-1zM17 23h1v1h-1zM17 24h1v1h-1zM31 24h1v1h-1zM37 24h1v1h-1zM19 25h1v1h-1zM32 25h5v1h-5zM38 25h1v1h-1zM20 26h1v1h-1zM11 27h1v1h-1zM20 27h1v1h-1zM39 27h1v1h-1zM23 28h1v1h-1zM12 29h1v1h-1zM25 29h1v1h-1zM13 30h1v1h-1zM24 31h1v1h-1zM14 32h1v1h-1zM23 32h1v1h-1zM23 33h1v1h-1zM21 34h2v1h-2zM20 35h1v1h-1zM19 36h1v1h-1z" />
      <path fill="#1D2B78" d="M24 0h6v1h-6zM20 1h4v1h-4zM30 1h4v1h-4zM18 2h2v1h-2zM34 2h2v1h-2zM16 3h2v1h-2zM36 3h2v1h-2zM15 4h1v1h-1zM38 4h1v1h-1zM14 5h1v1h-1zM39 5h1v1h-1zM13 6h1v1h-1zM40 6h1v1h-1zM12 7h1v1h-1zM41 7h1v1h-1zM42 8h1v1h-1zM9 12h1v1h-1zM8 13h1v1h-1zM45 13h1v1h-1zM8 14h1v1h-1zM45 14h1v1h-1zM8 15h1v1h-1zM45 15h1v1h-1zM8 16h1v1h-1zM45 16h1v1h-1zM7 17h1v1h-1zM46 17h1v1h-1zM7 18h1v1h-1zM46 18h1v1h-1zM7 19h1v1h-1zM46 19h1v1h-1zM7 20h1v1h-1zM46 20h1v1h-1zM7 21h1v1h-1zM46 21h1v1h-1zM7 22h1v1h-1zM46 22h1v1h-1zM8 23h1v1h-1zM45 23h1v1h-1zM8 24h1v1h-1zM45 24h1v1h-1zM8 25h1v1h-1zM45 25h1v1h-1zM8 26h1v1h-1zM45 26h1v1h-1zM9 27h1v1h-1zM44 27h1v1h-1zM9 28h1v1h-1zM44 28h1v1h-1zM10 29h1v1h-1zM43 29h1v1h-1zM10 30h1v1h-1zM43 30h1v1h-1zM11 31h1v1h-1zM42 31h1v1h-1zM12 32h1v1h-1zM41 32h1v1h-1zM13 33h1v1h-1zM14 34h1v1h-1zM15 35h1v1h-1zM16 36h2v1h-2zM18 37h2v1h-2zM20 38h4v1h-4zM30 38h4v1h-4zM24 39h6v1h-6z" />
      <path fill="#C4E6CC" d="M19 4h1v1h-1zM21 4h1v1h-1zM16 5h1v1h-1zM20 5h1v1h-1zM15 6h1v1h-1zM19 6h1v1h-1zM14 7h7v1h-7zM15 8h6v1h-6zM16 9h5v1h-5zM17 10h1v1h-1zM20 10h1v1h-1zM13 12h2v1h-2zM12 13h1v1h-1zM14 13h1v1h-1z" />
      <path fill="#96CBA9" d="M20 2h1v1h-1zM18 3h2v1h-2zM34 3h2v1h-2zM16 4h3v1h-3zM20 4h1v1h-1zM32 4h6v1h-6zM15 5h1v1h-1zM17 5h1v1h-1zM32 5h7v1h-7zM14 6h1v1h-1zM16 6h1v1h-1zM32 6h2v1h-2zM35 6h5v1h-5zM13 7h1v1h-1zM33 7h7v1h-7zM13 8h2v1h-2zM31 8h1v1h-1zM34 8h6v1h-6zM31 9h8v1h-8zM33 10h6v1h-6zM33 11h7v1h-7zM10 12h3v1h-3zM32 12h3v1h-3zM9 13h3v1h-3zM13 13h1v1h-1zM32 13h2v1h-2zM9 14h1v1h-1zM33 14h5v1h-5zM9 15h1v1h-1zM33 15h5v1h-5zM9 16h1v1h-1zM9 17h2v1h-2zM12 17h1v1h-1zM10 18h1v1h-1zM10 19h1v1h-1zM10 20h1v1h-1zM33 21h4v1h-4zM38 21h1v1h-1zM12 22h3v1h-3zM31 22h5v1h-5zM12 23h5v1h-5zM31 23h6v1h-6zM11 24h1v1h-1zM14 24h3v1h-3zM32 24h2v1h-2zM35 24h1v1h-1zM11 25h1v1h-1zM11 26h2v1h-2zM12 27h1v1h-1zM12 28h1v1h-1zM20 28h3v1h-3zM13 29h2v1h-2zM20 29h5v1h-5zM14 30h4v1h-4zM20 30h4v1h-4zM14 31h1v1h-1zM16 31h7v1h-7zM19 32h1v1h-1z" />
      <path fill="#6FAE88" d="M40 7h1v1h-1zM40 8h1v1h-1zM41 9h2v1h-2zM40 10h1v1h-1zM43 18h1v1h-1zM45 18h1v1h-1zM41 19h5v1h-5zM38 20h8v1h-8zM37 21h1v1h-1zM39 21h7v1h-7zM36 22h10v1h-10zM37 23h5v1h-5zM44 23h1v1h-1zM34 24h1v1h-1zM36 24h1v1h-1zM38 24h1v1h-1zM44 24h1v1h-1zM44 25h1v1h-1zM42 26h3v1h-3zM40 27h4v1h-4zM40 28h4v1h-4zM40 29h3v1h-3zM39 30h2v1h-2zM42 30h1v1h-1zM15 31h1v1h-1zM23 31h1v1h-1zM15 32h4v1h-4zM20 32h3v1h-3zM15 33h8v1h-8zM15 34h6v1h-6zM16 35h4v1h-4zM18 36h1v1h-1z" />
      <path fill="#5C9A72" d="M12 24h2v1h-2zM12 25h7v1h-7zM13 26h7v1h-7zM13 27h7v1h-7zM13 28h7v1h-7zM15 29h5v1h-5zM18 30h2v1h-2z" />
      <path fill="#4A8460" d="M42 23h2v1h-2zM39 24h5v1h-5zM39 25h5v1h-5zM39 26h3v1h-3z" />
      <path fill="#E2D09A" d="M38 15h3v1h-3zM33 16h7v1h-7zM32 17h7v1h-7zM31 18h7v1h-7zM31 19h8v1h-8zM31 20h7v1h-7zM31 21h2v1h-2z" />
      <path fill="#C8B37A" d="M42 13h3v1h-3zM40 14h5v1h-5zM41 15h4v1h-4zM40 16h4v1h-4zM39 17h7v1h-7zM38 18h5v1h-5zM44 18h1v1h-1zM39 19h2v1h-2zM41 30h1v1h-1zM39 31h3v1h-3zM39 32h2v1h-2z" />
      <path fill="#FFFFFF" d="M21 5h1v1h-1zM24 5h1v1h-1zM26 5h1v1h-1z" />
      <path fill="#E6EEF9" d="M21 2h5v1h-5zM24 3h4v1h-4zM24 4h4v1h-4zM25 5h1v1h-1zM24 6h1v1h-1zM28 6h1v1h-1z" />
      <path fill="#FFFFFF" d="M8 7h3v1h-3zM5 8h3v1h-3zM11 8h2v1h-2zM45 8h3v1h-3zM3 9h2v1h-2zM13 9h3v1h-3zM43 9h2v1h-2zM48 9h2v1h-2zM1 10h2v1h-2zM16 10h1v1h-1zM41 10h2v1h-2zM50 10h3v1h-3zM40 11h1v1h-1zM53 11h1v1h-1zM21 17h3v1h-3zM19 18h5v1h-5zM26 29h2v1h-2zM24 30h3v1h-3zM38 33h4v1h-4zM34 34h4v1h-4zM42 34h2v1h-2zM32 35h2v1h-2zM44 35h3v1h-3zM30 36h2v1h-2zM47 36h2v1h-2z" />
      <path fill="#DCE7F8" d="M8 8h3v1h-3zM5 9h8v1h-8zM45 9h3v1h-3zM3 10h13v1h-13zM43 10h7v1h-7zM41 11h12v1h-12zM24 18h2v1h-2zM27 30h3v1h-3zM38 34h4v1h-4zM34 35h10v1h-10zM32 36h15v1h-15z" />
      <path fill="#B7C0F0" d="M0 11h17v1h-17zM40 12h14v1h-14zM28 37h23v1h-23z" />
    </svg>
  );
}
